version: '3.1'

services:
  postgres:
    image: postgres:13.2-alpine
    container_name: rest_db
    environment:
      POSTGRES_DB: restdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
